run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - goconst
    - gocritic
    - gofmt
    - goimports
    - gosec
    - misspell
    - nilerr
    - prealloc
    - predeclared
    - revive
    - unconvert
    - unparam
    - whitespace

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
  revive:
    rules:
      - name: exported
        arguments:
          - checkPrivateReceivers
      - name: blank-imports
      - name: context-as-argument
      - name: error-return
      - name: error-strings
      - name: increment-decrement
      - name: var-declaration
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
    disabled-checks:
      - hugeParam
  gosec:
    excludes:
      - G104
      - G204

issues:
  max-issues-per-linter: 50
  max-same-issues: 10
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
        - gocritic
